import 'package:card_flow/models/card_model.dart';
import 'package:card_flow/services/card_service.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AddCardPage extends StatefulWidget {
  const AddCardPage({super.key});

  @override
  State<AddCardPage> createState() => _AddCardPageState();
}

class _AddCardPageState extends State<AddCardPage> {
  final _formKey = GlobalKey<FormState>();
  final _cardService = CardService();

  // Form field controllers
  final _aliasController = TextEditingController();
  final _lastFourController = TextEditingController();
  final _cvvController = TextEditingController();
  final _dueDayController = TextEditingController();
  final _bestDayController = TextEditingController();

  // Dropdown and switch values
  CardType _selectedType = CardType.PF;
  String _selectedBrand = 'Visa'; // Default value
  bool _isAutoPay = false;

  final List<String> _brands = ['Visa', 'Mastercard', 'Elo', 'American Express', 'Hipercard'];

  @override
  void dispose() {
    _aliasController.dispose();
    _lastFourController.dispose();
    _cvvController.dispose();
    _dueDayController.dispose();
    _bestDayController.dispose();
    super.dispose();
  }

  void _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Error: User not logged in.')),
        );
        return;
      }

      final newCard = CreditCard(
        id: '', // ID will be generated by Firestore
        userId: user.uid,
        alias: _aliasController.text,
        type: _selectedType,
        brand: _selectedBrand,
        dueDay: int.tryParse(_dueDayController.text) ?? 0,
        bestDay: int.tryParse(_bestDayController.text) ?? 0,
        isAutoPay: _isAutoPay,
        status: CardStatus.active,
        lastFourDigits: _lastFourController.text,
        cvv: _cvvController.text,
      );

      try {
        await _cardService.addCard(newCard);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Card added successfully!')),
          );
          Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Failed to add card: $e')),
          );
        }
      }
    }
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Card'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextFormField(
                controller: _aliasController,
                decoration: const InputDecoration(labelText: 'Card Name (e.g., Itaú Black)'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a name for the card';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                value: _selectedBrand,
                decoration: const InputDecoration(labelText: 'Brand'),
                items: _brands.map((String brand) {
                  return DropdownMenuItem<String>(
                    value: brand,
                    child: Text(brand),
                  );
                }).toList(),
                onChanged: (newValue) {
                  setState(() {
                    _selectedBrand = newValue!;
                  });
                },
              ),
              const SizedBox(height: 16),
               TextFormField(
                controller: _lastFourController,
                decoration: const InputDecoration(labelText: 'Last 4 Digits'),
                 keyboardType: TextInputType.number,
                 inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                 maxLength: 4,
                validator: (value) {
                  if (value == null || value.length != 4) {
                    return 'Please enter the last 4 digits';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _cvvController,
                decoration: const InputDecoration(labelText: 'CVV'),
                keyboardType: TextInputType.number,
                inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                maxLength: 3,
                obscureText: true,
                validator: (value) {
                  if (value == null || value.length != 3) {
                    return 'Please enter the 3-digit CVV';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _dueDayController,
                      decoration: const InputDecoration(labelText: 'Due Day'),
                      keyboardType: TextInputType.number,
                      inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                      validator: (value) {
                        if (value == null || value.isEmpty) return 'Required';
                        final day = int.tryParse(value);
                        if (day == null || day < 1 || day > 31) {
                          return 'Invalid day';
                        }
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                     child: TextFormField(
                      controller: _bestDayController,
                      decoration: const InputDecoration(labelText: 'Best Purchase Day'),
                      keyboardType: TextInputType.number,
                       inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                      validator: (value) {
                         if (value == null || value.isEmpty) return 'Required';
                         final day = int.tryParse(value);
                         if (day == null || day < 1 || day > 31) {
                           return 'Invalid day';
                         }
                         return null;
                       },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<CardType>(
                value: _selectedType,
                decoration: const InputDecoration(labelText: 'Type'),
                items: const [
                  DropdownMenuItem(value: CardType.PF, child: Text('Personal (PF)')),
                  DropdownMenuItem(value: CardType.PJ, child: Text('Business (PJ)')),
                ],
                onChanged: (newValue) {
                  setState(() {
                    _selectedType = newValue!;
                  });
                },
              ),
              const SizedBox(height: 16),
              SwitchListTile(
                title: const Text('Automatic Debit'),
                value: _isAutoPay,
                onChanged: (bool value) {
                  setState(() {
                    _isAutoPay = value;
                  });
                },
              ),
              const SizedBox(height: 32),
              Center(
                child: ElevatedButton(
                  onPressed: _submitForm,
                  child: const Text('Add Card'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
